version: '3.1'

services:

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://localhost:27017