version: '3.1'

services:

  app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - docker_config.env
    ports:
      - "8989:8989"
    depends_on:
      - mongo

  mongo:
    image: mongo
    env_file:
      - docker_config.env
    ports:
      - "27017:27017"  